### ISSUE TITLE
Pipfile -> setup.py not working

### ISSUE THREAD

**Issue by zicvic** [orsinium/install-requires#1]
If run with `pipenv run install-requires Pipfile setup.py` the following error occurs:
```
Traceback (most recent call last):
  File "/Users/USER/.local/share/virtualenvs/package-xT6cQEuA/bin/install-requires", line 8, in <module>
    sys.exit(convert())
  File "/Users/USER/.local/share/virtualenvs/package-xT6cQEuA/lib/python3.7/site-packages/install_requires/cli.py", line 21, in convert
    result = _convert(name_from, name_to, path)
  File "/Users/USER/.local/share/virtualenvs/package-xT6cQEuA/lib/python3.7/site-packages/install_requires/core.py", line 109, in convert
    return getattr(dumper(path), loader)()
  File "/Users/USER/.local/share/virtualenvs/package-xT6cQEuA/lib/python3.7/site-packages/install_requires/core.py", line 65, in from_pipfile
    packages = project.get_sections()['packages'].items()
  File "/Users/USER/.local/share/virtualenvs/package-xT6cQEuA/lib/python3.7/site-packages/requirementslib/models/pipfile.py", line 240, in __getattr__
    return super(Pipfile, self).__getattribute__(k, *args, **kwargs)
AttributeError: 'Pipfile' object has no attribute 'get_sections'
```

**Comment by orsinium** [comment]
Ah, I forgot about this project. Thank you, I'll archive it tomorrow. Please, use [DepHell](https://github.com/dephell/dephell) instead, it can do everything the same and much more. In particular, you need `deps convert` command. Good luck :)
